version: '3.4'

services:
  firestoreusers:
    image: firestoreuserdemo:latest
    build:
      context: .
    ports:
      - "5000:80"
    networks:
      - kevin-network
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "viagens-307823-0508a76800da.json"  

networks: 
    kevin-network:
        driver: bridge